### ISSUE TITLE
Documentation is sparse and very high level

### ISSUE THREAD

**Issue by michaeleisel** [overtone/overtone#290]
It's very hard to actually hack on a project without reading the source code for everything, because there's such little documentation and it's so high-level. For example, what does :ar mean? There's no explanation of it at all in the wiki.

**Comment by xdhmoore** [comment]
I second this request.  Maybe at least a general guide of where to go in the SuperCollider documentation to find the definition for things, even if it is a different language.

**Comment by plexus** [comment]
I'm going to close this since this is a rather old issue with not a clear single action to take. Hopefully things have already improved since 2014, and we'll be making the docs better as time goes on.

The examples are indeed a good way to explore Overtone, there's also a work-in-progress User Guide https://overtone.github.io/docs.html
