### ISSUE TITLE
Clojure/Conj 2011 presentation code

### ISSUE THREAD

**Issue by ghost** [overtone/overtone#314]
Hi, are all the examples from your 2011 Conj presentation available somewhere to study?

**Comment by plexus** [comment]
Most if it can be found under the examples/ directory, it's best to search for specific words or phrases like `wobble`, `thx`, `lh-pitches`, since some of it has moved around.

Some namespaces that Sam demonstrated

- overtone.examples.monome.satie
- overtone.examples.monome.sample-looper
- overtone.examples.instruments.thx
