### ISSUE TITLE
Overtone code completion in Cursive IDE

### ISSUE THREAD

**Issue by theronic** [overtone/overtone#365]
Playing around with the beautiful Overtone library in the Cursive IDE, but I can't seem to get any auto completion or inspection to work with Overtone. I tried to :require `overtone.core :as o`, but no luck. Any help? Maybe I'm doing something wrong - not an Emacs wizard either.

**Comment by hlolli** [comment]
The autocompletion in Emacs is due to Cider reading symbols from the clojure repl and displaying it with ac-mode/company-mode. There's no specific functionality within Overtone that supports or supresses code completions. It should work with Cursive just like any other Clojure library (or not work like no other Clojure library).
