### ISSUE TITLE
error scheduling midi messages with `at`

### ISSUE THREAD

**Issue by pablobcb** [overtone/overtone#445]
hello everyone, I'm trying to loop a simple 2 note sequence sending midi notes interchangeably, but the two notes are triggered at the function evaluation, not at the scheduled time

```
(def metro (metronome 150))

(defn player [beat]
  (at (metro beat) (m/midi-note midi-out (note :c2) 100 100 0))
  (at (metro (+ 0.50 beat)) (m/midi-note midi-out (note :g2) 100 100 0))
  (apply-by (metro (inc beat)) #'player (inc beat) []))

(player (metro))
```

I was able to use `at` with overtone internal instruments .. am I missing something? should I use `at-at`?

**Comment by karlthorssen** [comment]
Hi, I think you do need to use `at-at` here. `at` doesn't actually delay evaluation of clojure/java code, it sends a message to the supercollider server requesting a sound be played in the future. This is desirable because supercollider has better realtime facilities than the JVM.

In your case you are sending messages from the jvm to the midi receiver (out of curiousity, what is the your midi receiver?) and bypassing supercollider, so you will want to do the scheduling within clojure using at-at.

**Comment by pablobcb** [comment]
thanks for the response :)

Im currently trying to send messages midi messages to my eurorack system and my virus ti :) 
but Im just interested in the midi generation part

any tips on how to integrate at-at with metronome?

**Comment by pablobcb** [comment]
for the ppl interested
```
(defn player [beat]
  (at-at/at (metro beat) #(m/midi-note midi-out (note :c#2) 100 100 0) midi-pool)
  (at-at/at (metro (+ 0.50 beat)) #(m/midi-note midi-out (note :f#2) 100 100 0) midi-pool)
  (apply-by (metro (inc beat)) #'player (inc beat) []))
```
this works
