### ISSUE TITLE
`at` form seems to no longer work?

### ISSUE THREAD

**Issue by namin** [overtone/overtone#480]
Hi,

The `at` form seems to no longer play. Below `(quick-kick)` makes a sound, but not `(at (now) (quick-kick))`. 

```
(use 'overtone.live)
nil
user> (use ['overtone.inst.drum :only ['quick-kick]])
nil
user> (at (now) (quick-kick))
#<synth-node[loading]: overtone.inst.drum/quick-kick 1949>
user> (quick-kick)
#<synth-node[loading]: overtone.inst.drum/quick-kick 1989>
TOO LOUD!! (clipped) Bus: 1 - lower master vol
TOO LOUD!! (clipped) Bus: 0 - lower master vol
```

Thanks.

**Comment by namin** [comment]
I tried in Java 16 but also in Java 9.

**Comment by namin** [comment]
It works in v0.10.3 but not in v0.10.4.

**Comment by LarryLegend33** [comment]
Ha the two issues you've reported I'm having the exact same thing -- 405 error w/ freesound and scheduling no longer works.

**Comment by pfeodrippe** [comment]
@namin Which OS you are using?

In OSX, there were some issues with CoreAudio where the scheduling was unstable (https://github.com/supercollider/supercollider/issues/5168), it was fixed in version 3.11.2 (https://github.com/supercollider/supercollider/pull/5358), while we use scsynth 3.10.2 (https://github.com/overtone/scsynth), so we may have some work to do here.

**Comment by namin** [comment]
Good call. I am using Mac OS X.

**Comment by den1k** [comment]
running into this with the internal server boot but not external 🤷‍♂️

**Comment by plexus** [comment]
There have been a few releases since this issue was created. We no longer bundle an internal SuperCollider, you are expected to install it yourself (see https://groups.google.com/g/overtone/c/qndjDV5FS9Y for motivation).

I'm going to close this as it sounds like running with a recent SuperCollider fixes this. If this is still an issue feel free to open a new ticket. Thanks!
