### ISSUE TITLE
dlsym load err

### ISSUE THREAD

**Issue by Jumaku** [overtone/overtone#509]
Hey folks,
 
i am having a pretty frustrating time right now trying to get overtone to work. My project.clj file looks like that:

```
(defproject overtone-tutorial "1.0.0"
    :dependencies [[overtone/overtone "0.10.3"]]
      :native-path "native"
        :source-paths ["src"]
        :jvm-opts ^:replace [])
```

well and running `lein repl` gives me the following:

```
REPL server started on port 35955 on host 127.0.0.1 - nrepl://127.0.0.1:35955
REPL-y 0.5.1, nREPL 0.9.0
Clojure 1.9.0-alpha17
OpenJDK 64-Bit Server VM 21+35
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (use 'overtone.live)
--> Loading Overtone...
--> Booting internal SuperCollider server...
CompilerException java.lang.IllegalArgumentException: No matching method found: sleep, compiling:(overtone/live.clj:6:1)

user=> Found 18 LADSPA plugins
*** ERROR: dlsym load err '/home/juk/code/clojure/insane-noise/native/linux/x86_64/libscsynth.so: undefined symbol: load'
JackDriver: client name is 'SuperCollider'
SC_AudioDriver: sample rate = 48000.000000, driver's block size = 1024
Exception in World_OpenUDP: unable to bind udp socket

--> Connecting to internal SuperCollider server...
--> Connection established
```

It is somehow related to the libscsynth.so. I hope somebody can help.

EDIT: 

Ok so it was kind of stupid mistake. I installed jack-example-tools, pipewire, pipewire-alsa, pipewire-pulse and pipewire-jack and removed jack2, jack2-dbus, cadence. So basically following the approaches described in here:

https://savo.rocks/posts/pipewire-effortless-linux-audio/
https://savo.rocks/posts/overtone-basic-setup/

Starting QjackCtl before running (use 'overtone.live) now at least fixed the error related to libscsynth.so but still running into

```
--> Booting internal SuperCollider server...
CompilerException java.lang.IllegalArgumentException: No matching method found: sleep, compiling:(overtone/live.clj:6:1)
```

If somebody had a similar issue, I would really appreciate any help.

**Comment by Jumaku** [comment]
ok so for everybody stumbling across this. It seems like it is a bug that is fixed but not released yet:

https://github.com/overtone/overtone/pull/502

Switching to an earlier version of java could resolve the problem as well

**Comment by plexus** [comment]
Hi @Jumaku , thank you for trying out Overtone. I'm sorry for the bad experience you had.

There have been three new releases since this issue was posted. We dropped the internal supercollider server (you now need to make sure supercollider is installed on your system). This should eliminite any issues about "native" libraries.

The other issue you link to (#502) was an issue with newer JVMs, and has been fixed.

The README contains updated installation instructions, and I've added a [Linux Primer](https://github.com/overtone/overtone/wiki/Linux-Audio-Primer) to the wiki which might be helpful background info.

I'm going to close this issue as I believe the specific issues mentioned here are resolved, please give the latest version a try! And do open new issues if you encounter any more problems.
